fix(iOS): disable items
vonovak/react-navigation-header-buttons pull request #105
Opened 2020-12-09 20:37 UTC by brunohkbx

### Motivation
It's not possible to disable icons on iOS because the prop `enabled` isn't being passed to the `AnimatedBaseButton`

2020-12-09 21:36 UTC, vonovak commented
hi! thanks for the PR, how did you come to having this problem? Can you share some code that has this issue?

I'm asking because this example https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageDisabled.tsx

in the expo demo (https://expo.io/@vonovak/projects/navbar-buttons-demo) works fine for me, thanks!

2020-12-10 00:17 UTC, brunohkbx commented
@vonovak I just double-checked using this example and it's working fine on Android. However, on iOS I can press on the search icon even though it's `disabled`.

That's because android resolves to this component `TouchableItem.js` and the `TouchableNativeFeedback` accepts the prop `disabled`. However, iOS resolves to `TouchableItem.ios.js` and the `BaseButton` expect a prop [enabled](https://github.com/software-mansion/react-native-gesture-handler/blob/8809501f5095045bb5d9454a0ef858a68ea5bc5a/src/GestureHandlerPropTypes.js#L7).

Check this out:

```
headerRight: () => (
        <HeaderButtons HeaderButtonComponent={DisableableHeaderButton}>
          <Item title="search" iconName="ios-search" onPress={() => alert('A')} disabled />
          <Item title="select" onPress={() => alert('B')} />
        </HeaderButtons>
      ),
```

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/6487206/101704287-2614c200-3a63-11eb-9026-696a64c9ebb1.gif)

2020-12-15 19:54 UTC, brunohkbx commented
Hey @vonovak. Would you mind reviewing this PR again when you have a chance? Thanks :smile:

2020-12-16 17:53 UTC, vonovak requested changes

2020-12-16 17:53 UTC, vonovak commented on example/screens/UsageDisabled.tsx
> +    enabled={!props.disabled}
we should not be passing both disabled and enabled prop to a component. Please just pass disabled and use that in the Touchable, thanks!

2020-12-22 04:38 UTC, brunohkbx commented
@vonovak done :+1: You mean like so? Now `TouchableItem.ios.js` is using only the prop `disabled`

2020-12-23 00:41 UTC, vonovak approved these changes

2020-12-23 00:47 UTC, vonovak commented
I still think it's a bug in RNGH that `BaseButton` accepts `enabled` instead of `disabled` so I added that prop too for future compatibility. 

Thank you for the PR!

2020-12-23 00:48 UTC, merged